metrics = {
    "simSeconds": "SimSecond",
    "simTicks": "SimTick",
    "simInsts": "SimIns",
    "simOps": "SimOp",
    "hostInstRate": "HstInsRate",
    "hostOpRate": "HstOpRate",
    "board.processor.cores.core.cpi": "CPU_CPI",
    "board.processor.cores.core.ipc": "CPU_IPC",
    # # For from gem5.components.cachehierarchies.classic.private_l1_private_l2_cache_hierarchy import PrivateL1PrivateL2CacheHierarchy
    # "board.cache_hierarchy.l1i-cache-0.overallHits::total": "L1i_TotHits",
    # "board.cache_hierarchy.l1i-cache-0.overallMisses::total": "L1i_TotMisses",
    # "board.cache_hierarchy.l1i-cache-0.overallMissRate::total": "L1i_TotMissRate",
    # "board.cache_hierarchy.l1i-cache-0.overallAvgMissLatency::total": "L1i_TotAvgMissLat",
    # "board.cache_hierarchy.l1d-cache-0.overallHits::total": "L1d_TotHits",
    # "board.cache_hierarchy.l1d-cache-0.overallMisses::total": "L1d_TotMisses",
    # "board.cache_hierarchy.l1d-cache-0.overallMissRate::total": "L1d_TotMissRate",
    # "board.cache_hierarchy.l1d-cache-0.overallAvgMissLatency::total": "L1d_TotAvgMissLat",
    # "board.cache_hierarchy.l1d-cache-0.ReadReq.hits::total": "L1d_ReadReqHits",
    # "board.cache_hierarchy.l1d-cache-0.ReadReq.misses::total": "L1d_ReadReqMisses",
    # "board.cache_hierarchy.l1d-cache-0.ReadReq.missRate::total": "L1d_ReadReqMissRate",
    # "board.cache_hierarchy.l1d-cache-0.ReadReq.avgMissLatency::total": "L1d_ReadReqAvgMissLat",
    # "board.cache_hierarchy.l1d-cache-0.WriteReq.hits::total": "L1d_WriteReqHits",
    # "board.cache_hierarchy.l1d-cache-0.WriteReq.misses::total": "L1d_WriteReqMisses",
    # "board.cache_hierarchy.l1d-cache-0.WriteReq.missRate::total": "L1d_WriteReqMissRate",
    # "board.cache_hierarchy.l1d-cache-0.WriteReq.avgMissLatency::total": "L1d_WriteReqAvgMissLat",
    # "board.cache_hierarchy.l2-cache-0.overallHits::total": "L2_TotHits",
    # "board.cache_hierarchy.l2-cache-0.overallMisses::total": "L2_TotMisses",
    # "board.cache_hierarchy.l2-cache-0.overallMissRate::total": "L2_TotMissRate",
    # "board.cache_hierarchy.l2-cache-0.overallAvgMissLatency::total": "L2_TotAvgMissLat",
    # For riscvmatched_cache
    "board.cache_hierarchy.l1icaches.overallHits::total": "L1i_TotHits",
    "board.cache_hierarchy.l1icaches.overallMisses::total": "L1i_TotMisses",
    "board.cache_hierarchy.l1icaches.overallMissRate::total": "L1i_TotMissRate",
    "board.cache_hierarchy.l1icaches.overallAvgMissLatency::total": "L1i_TotAvgMissLat",
    "board.cache_hierarchy.l1dcaches.overallHits::total": "L1d_TotHits",
    "board.cache_hierarchy.l1dcaches.overallMisses::total": "L1d_TotMisses",
    "board.cache_hierarchy.l1dcaches.overallMissRate::total": "L1d_TotMissRate",
    "board.cache_hierarchy.l1dcaches.overallAvgMissLatency::total": "L1d_TotAvgMissLat",
    "board.cache_hierarchy.l1dcaches.ReadReq.hits::total": "L1d_ReadReqHits",
    "board.cache_hierarchy.l1dcaches.ReadReq.misses::total": "L1d_ReadReqMisses",
    "board.cache_hierarchy.l1dcaches.ReadReq.missRate::total": "L1d_ReadReqMissRate",
    "board.cache_hierarchy.l1dcaches.ReadReq.avgMissLatency::total": "L1d_ReadReqAvgMissLat",
    "board.cache_hierarchy.l1dcaches.WriteReq.hits::total": "L1d_WriteReqHits",
    "board.cache_hierarchy.l1dcaches.WriteReq.misses::total": "L1d_WriteReqMisses",
    "board.cache_hierarchy.l1dcaches.WriteReq.missRate::total": "L1d_WriteReqMissRate",
    "board.cache_hierarchy.l1dcaches.WriteReq.avgMissLatency::total": "L1d_WriteReqAvgMissLat",
    "board.cache_hierarchy.l2cache.overallHits::total": "L2_TotHits",
    "board.cache_hierarchy.l2cache.overallMisses::total": "L2_TotMisses",
    "board.cache_hierarchy.l2cache.overallMissRate::total": "L2_TotMissRate",
    "board.cache_hierarchy.l2cache.overallAvgMissLatency::total": "L2_TotAvgMissLat",
}
